INSERT INTO students 
VALUES
('Bryant', 'Beeler'),
('Victor', 'Blacknall'),
('Toby', 'Blanchard'),
('Tyler', 'Campbell'),
('Aleya', 'Chowdhury'),
('Dina', 'Dunn'),
('Amos', 'Gichero'),
('Shane', 'Hall'),
('Branden', 'Hart'),
('Azadeh', 'Hashemi'),
('John', 'Hill'),
('Tawni', 'Hollers'),
('Donell', 'Hubbard'),
('Bob', 'Igbarumah'),
('Noelle', 'Irvin'),
('Andrew', 'Johnson'),
('Robert', 'Kee'),
('Juho', 'Lee'),
('Shahar', 'Levy'),
('Mariano', 'Lino'),
('Mayur', 'Maisuria'),
('Amber', 'Marshall'),
('Calder', 'Marshall'),
('Hunter', 'McAfee'),
('Josslyn', 'Oringi'),
('Rosslyn', 'Oringi'),
('Jonathan', 'Rodriguez'),
('NaDario', 'Seays'),
('Newsha', 'Tavakoli'),
('Junior', 'Tirimboi'),
('Tahrim', 'Uddin'),
('Christian', 'Walker')
;
